name: Daily Commit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: miryala@straive.com
      run: |
        echo "Hello, world!"
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "miryala@straive.com"

    - name: Create a commit
      run: |
        echo "Daily update: $(date)" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit by GitHub Actions"
        git push
