name: Build and Push Docker Image with Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a sample Dockerfile
      run: |
        echo "FROM alpine:3.17" > Dockerfile
        echo "CMD [\"echo\", \"Hello from a tagged Docker image!\"]" >> Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: narayanareddy123/sample-image:miryala.narayanareddy
